import { FoodItem } from '@/types/store';

export const STORE_CATEGORIES = [
  { id: 'all', name: 'All Menu', icon: '🍽️' },
  { id: 'burgers', name: 'Burgers & Wraps', icon: '🍔' },
  { id: 'pizzas', name: 'Artisan Pizzas', icon: '🍕' },
  { id: 'asian', name: 'Asian Bowls', icon: '🍜' },
  { id: 'mexican', name: 'Tacos & Burritos', icon: '🌮' },
  { id: 'desserts', name: 'Desserts & Bakes', icon: '🍰' },
  { id: 'beverages', name: 'Drinks & Brews', icon: '🥤' },
] as const;

export const MENU_ITEMS: FoodItem[] = [
  // Burgers
  {
    id: 'truffle-burger',
    name: 'Smoked Truffle Smash Burger',
    category: 'burgers',
    price: 14.99,
    rating: 4.9,
    reviewsCount: 382,
    prepTime: '15-20 min',
    calories: 680,
    icon: '🍔',
    badge: 'Bestseller',
    description: 'Double Angus beef patties, aged gruyère, black truffle aioli, caramelized onions on toasted brioche.',
    isVegetarian: false,
  },
  {
    id: 'crispy-chicken-burger',
    name: 'Nashville Hot Crispy Chicken',
    category: 'burgers',
    price: 12.99,
    rating: 4.8,
    reviewsCount: 245,
    prepTime: '12-18 min',
    calories: 720,
    icon: '🍗',
    badge: 'Spicy',
    description: 'Buttermilk fried chicken tossed in cayenne glaze, house pickles, garlic slaw, brioche bun.',
    isVegetarian: false,
  },
  {
    id: 'plant-avo-burger',
    name: 'Avocado Beyond Patty',
    category: 'burgers',
    price: 13.49,
    rating: 4.7,
    reviewsCount: 120,
    prepTime: '12-16 min',
    calories: 520,
    icon: '🥑',
    badge: 'Vegan',
    description: 'Char-grilled 100% plant patty, fresh avocado mash, vegan cheddar, butter lettuce, tomato relish.',
    isVegetarian: true,
  },

  // Pizzas
  {
    id: 'margherita-burrata',
    name: 'Burrata Margherita D.O.P.',
    category: 'pizzas',
    price: 16.99,
    rating: 4.9,
    reviewsCount: 512,
    prepTime: '18-25 min',
    calories: 840,
    icon: '🍕',
    badge: "Chef's Pick",
    description: 'San Marzano tomato base, creamy whole burrata, fior di latte, fresh sweet basil, EVOO drizzle.',
    isVegetarian: true,
  },
  {
    id: 'diavola-pepperoni',
    name: 'Double Hot Pepperoni Diavola',
    category: 'pizzas',
    price: 17.49,
    rating: 4.8,
    reviewsCount: 420,
    prepTime: '20-25 min',
    calories: 960,
    icon: '🍕',
    badge: 'Popular',
    description: 'Spicy artisanal pepperoni, Calabrian chili oil, hot honey drizzle, smoked provolone.',
    isVegetarian: false,
  },
  {
    id: 'wild-mushroom-pizza',
    name: 'Wild Forest Truffle Funghi',
    category: 'pizzas',
    price: 18.29,
    rating: 4.9,
    reviewsCount: 290,
    prepTime: '18-22 min',
    calories: 780,
    icon: '🍄',
    badge: 'Gourmet',
    description: 'Roasted portobello & chanterelles, taleggio cheese, thyme, white truffle cream.',
    isVegetarian: true,
  },

  // Asian
  {
    id: 'tonkotsu-ramen',
    name: '24hr Rich Tonkotsu Ramen',
    category: 'asian',
    price: 15.99,
    rating: 4.9,
    reviewsCount: 630,
    prepTime: '15-20 min',
    calories: 740,
    icon: '🍜',
    badge: 'Trending',
    description: 'Silky pork bone broth, braised chashu pork belly, ajitsuke tamago egg, menma, scallions, nori.',
    isVegetarian: false,
  },
  {
    id: 'teriyaki-salmon-bowl',
    name: 'Glazed Salmon Teriyaki Bowl',
    category: 'asian',
    price: 16.50,
    rating: 4.8,
    reviewsCount: 310,
    prepTime: '14-18 min',
    calories: 610,
    icon: '🍱',
    badge: 'Healthy',
    description: 'Pan-seared Atlantic salmon in house mirin glaze, jasmine rice, edamame, pickled ginger, sesame.',
    isVegetarian: false,
  },
  {
    id: 'tofu-pad-thai',
    name: 'Bangkok Tamarind Pad Thai',
    category: 'asian',
    price: 13.99,
    rating: 4.7,
    reviewsCount: 215,
    prepTime: '12-16 min',
    calories: 550,
    icon: '🥢',
    badge: 'Vegan Option',
    description: 'Stir-fried rice noodles, golden crispy tofu, crushed peanuts, beansprouts, lime wedge.',
    isVegetarian: true,
  },

  // Mexican
  {
    id: 'birria-tacos',
    name: 'Slow-Cooked Beef Birria Tacos (3 pcs)',
    category: 'mexican',
    price: 14.50,
    rating: 4.9,
    reviewsCount: 478,
    prepTime: '12-16 min',
    calories: 690,
    icon: '🌮',
    badge: 'Must Try',
    description: 'Braised beef in chili consome, melted cheese inside pan-crisped corn tortillas, onion & cilantro, side broth.',
    isVegetarian: false,
  },
  {
    id: 'carnitas-burrito-bowl',
    name: 'Loaded Carnitas Burrito Bowl',
    category: 'mexican',
    price: 13.99,
    rating: 4.8,
    reviewsCount: 340,
    prepTime: '10-15 min',
    calories: 620,
    icon: '🥗',
    description: 'Citrus slow-braised pork, cilantro-lime rice, black beans, pico de gallo, guacamole, crema.',
    isVegetarian: false,
  },

  // Desserts
  {
    id: 'matcha-tiramisu',
    name: 'Uji Matcha Tiramisu Jar',
    category: 'desserts',
    price: 7.99,
    rating: 4.9,
    reviewsCount: 195,
    prepTime: 'Ready',
    calories: 380,
    icon: '🍰',
    badge: 'Sweet',
    description: 'Japanese ceremonial grade matcha soaked ladyfingers layered with velvety mascarpone sabayon.',
    isVegetarian: true,
  },
  {
    id: 'molten-lava-cake',
    name: 'Valrhona Molten Lava Cake',
    category: 'desserts',
    price: 8.50,
    rating: 4.8,
    reviewsCount: 260,
    prepTime: '8-10 min',
    calories: 490,
    icon: '🍫',
    description: 'Warm dark chocolate cake with a molten fudge center, dusted with cacao powder.',
    isVegetarian: true,
  },

  // Beverages
  {
    id: 'cold-brew-latte',
    name: 'Salted Caramel Cold Brew',
    category: 'beverages',
    price: 5.49,
    rating: 4.8,
    reviewsCount: 340,
    prepTime: 'Ready',
    calories: 180,
    icon: '☕',
    description: '16hr slow-steeped Arabica coffee topped with silky salted caramel sweet cream.',
    isVegetarian: true,
  },
  {
    id: 'dragonfruit-lemonade',
    name: 'Sparkling Dragonfruit Refresher',
    category: 'beverages',
    price: 4.99,
    rating: 4.7,
    reviewsCount: 180,
    prepTime: 'Ready',
    calories: 120,
    icon: '🥤',
    description: 'Fresh dragonfruit puree, organic cold-pressed lemonade, sparkling water, mint leaves.',
    isVegetarian: true,
  },
];
