import { FoodItem } from '@/types/store';

export const STORE_CATEGORIES = [
  { id: 'all', name: 'All Essentials', icon: '⚡' },
  { id: 'dairy', name: 'Dairy, Bread & Eggs', icon: '🥛' },
  { id: 'snacks', name: 'Snacks & Munchies', icon: '🥨' },
  { id: 'drinks', name: 'Cold Drinks & Juices', icon: '🥤' },
  { id: 'veggies', name: 'Vegetables & Fruits', icon: '🥦' },
  { id: 'instant', name: 'Instant & Frozen Food', icon: '🍜' },
  { id: 'sweets', name: 'Ice Creams & Sweets', icon: '🍫' },
  { id: 'bakery', name: 'Bakery & Biscuits', icon: '🍪' },
] as const;

export const MENU_ITEMS: FoodItem[] = [
  // Dairy, Bread & Eggs
  {
    id: 'amul-taaza-milk',
    name: 'Amul Taaza Homogenised Toned Milk',
    category: 'dairy',
    price: 27,
    originalPrice: 28,
    unit: '500 ml',
    rating: 4.9,
    reviewsCount: 14200,
    prepTime: '8 MINS',
    icon: '🥛',
    badge: 'Bestseller',
    description: 'Fresh and nutritious toned milk, pasteurised and homogenised for everyday freshness.',
    isVegetarian: true,
  },
  {
    id: 'harvest-gold-bread',
    name: 'Harvest Gold White Sandwich Bread',
    category: 'dairy',
    price: 25,
    originalPrice: 30,
    unit: '400 g',
    rating: 4.8,
    reviewsCount: 8900,
    prepTime: '8 MINS',
    icon: '🍞',
    badge: 'Daily Essential',
    description: 'Soft, oven-fresh sandwich bread enriched with essential vitamins and calcium.',
    isVegetarian: true,
  },
  {
    id: 'farm-fresh-eggs',
    name: 'Farm Fresh White Eggs (Pack of 6)',
    category: 'dairy',
    price: 52,
    originalPrice: 60,
    unit: '6 pcs',
    rating: 4.8,
    reviewsCount: 6500,
    prepTime: '8 MINS',
    icon: '🥚',
    badge: 'Farm Fresh',
    description: 'Nutritious farm fresh graded eggs, packed with protein and wholesome vitality.',
    isVegetarian: false,
  },
  {
    id: 'mother-dairy-paneer',
    name: 'Mother Dairy Classic Malai Paneer',
    category: 'dairy',
    price: 88,
    originalPrice: 95,
    unit: '200 g',
    rating: 4.9,
    reviewsCount: 5200,
    prepTime: '8 MINS',
    icon: '🧀',
    badge: 'Popular',
    description: 'Pristine soft malai paneer crafted from wholesome cow and buffalo milk.',
    isVegetarian: true,
  },
  {
    id: 'amul-butter',
    name: 'Amul Salted Table Butter',
    category: 'dairy',
    price: 56,
    originalPrice: 58,
    unit: '100 g',
    rating: 4.9,
    reviewsCount: 11000,
    prepTime: '8 MINS',
    icon: '🧈',
    description: 'The utterly butterly delicious salted spread loved across all breakfasts.',
    isVegetarian: true,
  },

  // Snacks & Munchies
  {
    id: 'lays-magic-masala',
    name: "Lay's India's Magic Masala Potato Chips",
    category: 'snacks',
    price: 20,
    unit: '50 g',
    rating: 4.9,
    reviewsCount: 18400,
    prepTime: '8 MINS',
    icon: '🥔',
    badge: 'Must Have',
    description: 'Crispy wafer-thin potato chips tossed in an exotic blend of spicy Indian seasoning.',
    isVegetarian: true,
  },
  {
    id: 'doritos-cheese-nachos',
    name: 'Doritos Cheese Supreme Nacho Crisps',
    category: 'snacks',
    price: 50,
    originalPrice: 60,
    unit: '90 g',
    rating: 4.7,
    reviewsCount: 4200,
    prepTime: '8 MINS',
    icon: '🧀',
    badge: '17% OFF',
    description: 'Intense cheesy crunch made from real stone-ground sun-ripened corn.',
    isVegetarian: true,
  },
  {
    id: 'haldirams-bhujia',
    name: "Haldiram's Nagpur Aloo Bhujia",
    category: 'snacks',
    price: 45,
    originalPrice: 52,
    unit: '150 g',
    rating: 4.8,
    reviewsCount: 7800,
    prepTime: '8 MINS',
    icon: '🥨',
    description: 'Classic spicy potato noodle savory snack infused with mint and mild spices.',
    isVegetarian: true,
  },
  {
    id: 'act-ii-butter-popcorn',
    name: 'ACT II Instant Golden Butter Popcorn',
    category: 'snacks',
    price: 35,
    originalPrice: 40,
    unit: '70 g',
    rating: 4.8,
    reviewsCount: 3100,
    prepTime: '8 MINS',
    icon: '🍿',
    badge: 'Movie Night',
    description: 'Hot, fluffy movie-theater style popcorn popping in rich aromatic golden butter.',
    isVegetarian: true,
  },

  // Cold Drinks & Juices
  {
    id: 'coca-cola-zero',
    name: 'Coca-Cola Zero Sugar Soft Drink Can',
    category: 'drinks',
    price: 40,
    unit: '300 ml',
    rating: 4.8,
    reviewsCount: 9200,
    prepTime: '8 MINS',
    icon: '🥤',
    badge: 'Chilled',
    description: 'Great Coca-Cola taste with zero calories and zero sugar. Delivered ice cold.',
    isVegetarian: true,
  },
  {
    id: 'raw-pressery-coconut',
    name: 'Raw Pressery 100% Pure Tender Coconut Water',
    category: 'drinks',
    price: 65,
    originalPrice: 75,
    unit: '200 ml',
    rating: 4.9,
    reviewsCount: 3400,
    prepTime: '8 MINS',
    icon: '🥥',
    badge: '13% OFF',
    description: 'Naturally hydrating tender coconut water with zero added preservatives.',
    isVegetarian: true,
  },
  {
    id: 'red-bull-energy',
    name: 'Red Bull Energy Drink Can',
    category: 'drinks',
    price: 125,
    unit: '250 ml',
    rating: 4.9,
    reviewsCount: 8100,
    prepTime: '8 MINS',
    icon: '⚡',
    badge: 'Energy',
    description: 'Vitalizes body and mind with premium taurine, B-group vitamins and caffeine.',
    isVegetarian: true,
  },
  {
    id: 'frooti-mango-drink',
    name: 'Frooti Fresh Mango Juice Tetrapack',
    category: 'drinks',
    price: 20,
    unit: '160 ml',
    rating: 4.7,
    reviewsCount: 4600,
    prepTime: '8 MINS',
    icon: '🥭',
    description: 'Refreshing real Alphonso mango pulp beverage bursting with natural sweetness.',
    isVegetarian: true,
  },

  // Vegetables & Fruits
  {
    id: 'fresh-tomatoes',
    name: 'Fresh Hybrid Red Tomatoes',
    category: 'veggies',
    price: 36,
    originalPrice: 45,
    unit: '1 kg',
    rating: 4.8,
    reviewsCount: 12300,
    prepTime: '8 MINS',
    icon: '🍅',
    badge: 'Farm Fresh',
    description: 'Plump, ripe and firm farm-harvested tomatoes ideal for rich gravies and fresh salads.',
    isVegetarian: true,
  },
  {
    id: 'fresh-onions',
    name: 'Fresh Premium Grade Nashik Onions',
    category: 'veggies',
    price: 42,
    originalPrice: 50,
    unit: '1 kg',
    rating: 4.7,
    reviewsCount: 15600,
    prepTime: '8 MINS',
    icon: '🧅',
    badge: '16% OFF',
    description: 'Crisp and pungent top-grade onions, directly procured from Maharashtra farms.',
    isVegetarian: true,
  },
  {
    id: 'fresh-apples',
    name: 'Himachal Royal Gala Crisp Red Apples',
    category: 'veggies',
    price: 139,
    originalPrice: 165,
    unit: '4 pcs (approx 600 g)',
    rating: 4.9,
    reviewsCount: 3800,
    prepTime: '8 MINS',
    icon: '🍎',
    badge: 'Crisp & Sweet',
    description: 'Hand-picked juicy sweet mountain apples with high fiber and natural antioxidants.',
    isVegetarian: true,
  },
  {
    id: 'fresh-bananas',
    name: 'Robusta Golden Ripe Bananas',
    category: 'veggies',
    price: 48,
    originalPrice: 55,
    unit: '6 pcs',
    rating: 4.8,
    reviewsCount: 7100,
    prepTime: '8 MINS',
    icon: '🍌',
    description: 'Naturally sweetened energy-rich bananas, perfect for breakfast smoothies.',
    isVegetarian: true,
  },

  // Instant Food
  {
    id: 'maggi-masala-noodles',
    name: 'Maggi 2-Minute Masala Instant Noodles (Pack of 4)',
    category: 'instant',
    price: 56,
    originalPrice: 60,
    unit: '280 g',
    rating: 4.9,
    reviewsCount: 22400,
    prepTime: '8 MINS',
    icon: '🍜',
    badge: 'Bestseller',
    description: "India's favorite comfort meal crafted with roasted spices and wholesome goodness.",
    isVegetarian: true,
  },
  {
    id: 'yippee-noodles',
    name: 'Sunfeast YiPPee! Magic Masala Noodles',
    category: 'instant',
    price: 48,
    originalPrice: 55,
    unit: '240 g',
    rating: 4.7,
    reviewsCount: 5400,
    prepTime: '8 MINS',
    icon: '🥢',
    description: 'Non-sticky round noodles infused with real dehydrated veggies and rich blend spices.',
    isVegetarian: true,
  },
  {
    id: 'knorr-hot-sour-soup',
    name: 'Knorr Classic Chinese Hot & Sour Veg Soup',
    category: 'instant',
    price: 38,
    originalPrice: 42,
    unit: '43 g',
    rating: 4.7,
    reviewsCount: 2900,
    prepTime: '8 MINS',
    icon: '🥣',
    description: 'Restaurant-style appetizing spicy and tangy vegetable soup ready in 3 minutes.',
    isVegetarian: true,
  },

  // Sweets & Ice Cream
  {
    id: 'cadbury-silk',
    name: 'Cadbury Dairy Milk Silk Chocolate Bar',
    category: 'sweets',
    price: 80,
    originalPrice: 90,
    unit: '60 g',
    rating: 4.9,
    reviewsCount: 16700,
    prepTime: '8 MINS',
    icon: '🍫',
    badge: 'Indulgent',
    description: 'Velvety smooth, melt-in-mouth milk chocolate crafted for pure blissful indulgence.',
    isVegetarian: true,
  },
  {
    id: 'kwality-walls-feast',
    name: "Kwality Wall's Dark Chocolate Feast Ice Cream Stick",
    category: 'sweets',
    price: 45,
    originalPrice: 50,
    unit: '70 ml',
    rating: 4.9,
    reviewsCount: 8800,
    prepTime: '8 MINS',
    icon: '🍦',
    badge: 'Frozen Treat',
    description: 'Crunchy chocolate biscuit core coated in smooth chocolate ice cream and crackling shell.',
    isVegetarian: true,
  },
  {
    id: 'nutella-spread',
    name: 'Nutella Hazelnut Spread with Cocoa',
    category: 'sweets',
    price: 219,
    originalPrice: 245,
    unit: '350 g',
    rating: 4.9,
    reviewsCount: 6400,
    prepTime: '8 MINS',
    icon: '🌰',
    badge: '11% OFF',
    description: 'Creamy artisanal hazelnut and cocoa spread, irresistible on toast, pancakes, and waffles.',
    isVegetarian: true,
  },

  // Bakery & Biscuits
  {
    id: 'britannia-good-day',
    name: 'Britannia Good Day Cashew Cookies',
    category: 'bakery',
    price: 32,
    originalPrice: 35,
    unit: '200 g',
    rating: 4.8,
    reviewsCount: 9600,
    prepTime: '8 MINS',
    icon: '🍪',
    badge: 'Chai Time',
    description: 'Buttery crunchy cookies studded with generous real roasted cashew nuts.',
    isVegetarian: true,
  },
  {
    id: 'parle-g-original',
    name: 'Parle-G Original Gluco Biscuits Family Pack',
    category: 'bakery',
    price: 30,
    unit: '350 g',
    rating: 4.9,
    reviewsCount: 28000,
    prepTime: '8 MINS',
    icon: '🥠',
    badge: 'Legendary',
    description: "The nation's tea-time staple packed with the nourishing power of milk and wheat.",
    isVegetarian: true,
  },
  {
    id: 'oreo-vanilla-creme',
    name: 'Cadbury Oreo Original Vanilla Creme Biscuits',
    category: 'bakery',
    price: 40,
    originalPrice: 45,
    unit: '120 g',
    rating: 4.8,
    reviewsCount: 11200,
    prepTime: '8 MINS',
    icon: '🍪',
    description: 'Rich dark cocoa biscuits sandwiched with smooth signature vanilla cream.',
    isVegetarian: true,
  },
];
